.java_docker :
  image : openjdk:17.0.1-jdk
  tags :
    - docker

publish :
  stage : deploy
  extends : .java_docker
  script :
    - export PUBLIC_RELEASE_BUILD="true" || 1
    - export PUBLIC_RELEASE_BUILD_TOKEN="${LABYMOD_RELEASE_INTERN_TOKEN}" || exit 1
    - export BEARER_TOKEN="${LABYMOD_BEARER_TOKEN}" || exit 1
    - sh gradlew build --full-stacktrace
    - sh gradlew createReleaseJar --full-stacktrace
    - cp build/libs/release-* addon.jar
  only :
    - web
  artifacts :
    paths :
      - addon.jar
  when : on_success
